"""Add avatar table

Revision ID: 06fae314a73b
Revises: 2b068bcd46a9
Create Date: 2026-08-07 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06fae314a73b"
down_revision: Union[str, Sequence[str], None] = "2b068bcd46a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatar",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=24), nullable=False),
        sa.Column("original_key", sa.String(length=512), nullable=False),
        sa.Column("avatar_400_key", sa.String(length=512), nullable=True),
        sa.Column("avatar_100_key", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processing",
                "ready",
                "failed",
                name="avatar_status",
                create_constraint=True,
            ),
            nullable=False,
            server_default="processing",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_avatar_user_id"),
    )
    op.create_index(op.f("ix_avatar_id"), "avatar", ["id"], unique=False)
    op.create_index(op.f("ix_avatar_user_id"), "avatar", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_avatar_user_id"), table_name="avatar")
    op.drop_index(op.f("ix_avatar_id"), table_name="avatar")
    op.drop_table("avatar")
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS avatar_status")
    # ### end Alembic commands ###
