"""Create initial models

Revision ID: 12999bb9ce7c
Revises:
Create Date: 2026-08-05 12:21:01.986882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12999bb9ce7c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=True)
    op.create_table(
        "badge",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "badge_type",
            sa.Enum("FAME", "SHAME", name="badge_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column("author_id", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_badge_author_id"), "badge", ["author_id"], unique=False)
    op.create_index(op.f("ix_badge_id"), "badge", ["id"], unique=False)
    op.create_index(op.f("ix_badge_name"), "badge", ["name"], unique=False)
    op.create_table(
        "session",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=24), nullable=False),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("useragent", sa.Text(), nullable=True),
        sa.Column("terminated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_id"), "session", ["id"], unique=False)
    op.create_index(op.f("ix_session_user_id"), "session", ["user_id"], unique=False)
    op.create_table(
        "story",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_story_author_id"), "story", ["author_id"], unique=False)
    op.create_index(op.f("ix_story_id"), "story", ["id"], unique=False)
    op.create_table(
        "badge_story",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("badge_id", sa.String(length=24), nullable=False),
        sa.Column("story_id", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["badge_id"], ["badge.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_id"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("badge_id", "story_id", name="uq_badge_story"),
    )
    op.create_index(
        op.f("ix_badge_story_badge_id"), "badge_story", ["badge_id"], unique=False
    )
    op.create_index(op.f("ix_badge_story_id"), "badge_story", ["id"], unique=False)
    op.create_index(
        op.f("ix_badge_story_story_id"), "badge_story", ["story_id"], unique=False
    )
    op.create_table(
        "user_badge",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=24), nullable=False),
        sa.Column("badge_id", sa.String(length=24), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STRIVES",
                "HAS",
                "NOT",
                name="user_badge_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["badge_id"], ["badge.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),
    )
    op.create_index(
        op.f("ix_user_badge_badge_id"), "user_badge", ["badge_id"], unique=False
    )
    op.create_index(op.f("ix_user_badge_id"), "user_badge", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_badge_user_id"), "user_badge", ["user_id"], unique=False
    )
    op.create_table(
        "user_story",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.String(length=24), nullable=False),
        sa.Column("story_id", sa.String(length=24), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["story_id"], ["story.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "story_id", name="uq_user_story"),
    )
    op.create_index(op.f("ix_user_story_id"), "user_story", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_story_story_id"), "user_story", ["story_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_story_user_id"), "user_story", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_story_user_id"), table_name="user_story")
    op.drop_index(op.f("ix_user_story_story_id"), table_name="user_story")
    op.drop_index(op.f("ix_user_story_id"), table_name="user_story")
    op.drop_table("user_story")
    op.drop_index(op.f("ix_user_badge_user_id"), table_name="user_badge")
    op.drop_index(op.f("ix_user_badge_id"), table_name="user_badge")
    op.drop_index(op.f("ix_user_badge_badge_id"), table_name="user_badge")
    op.drop_table("user_badge")
    op.drop_index(op.f("ix_badge_story_story_id"), table_name="badge_story")
    op.drop_index(op.f("ix_badge_story_id"), table_name="badge_story")
    op.drop_index(op.f("ix_badge_story_badge_id"), table_name="badge_story")
    op.drop_table("badge_story")
    op.drop_index(op.f("ix_story_id"), table_name="story")
    op.drop_index(op.f("ix_story_author_id"), table_name="story")
    op.drop_table("story")
    op.drop_index(op.f("ix_session_user_id"), table_name="session")
    op.drop_index(op.f("ix_session_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_badge_name"), table_name="badge")
    op.drop_index(op.f("ix_badge_id"), table_name="badge")
    op.drop_index(op.f("ix_badge_author_id"), table_name="badge")
    op.drop_table("badge")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
