"""Add display_name and username change tracking to User

Revision ID: 2b068bcd46a9
Revises: 12999bb9ce7c
Create Date: 2026-08-05 14:01:36.857957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b068bcd46a9"
down_revision: Union[str, Sequence[str], None] = "12999bb9ce7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("display_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "username_change_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "user",
        sa.Column("last_username_change", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_username_change")
    op.drop_column("user", "username_change_count")
    op.drop_column("user", "display_name")
    # ### end Alembic commands ###
