name: Lint Code Base
on:
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync

      - name: Set up pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit hooks
        continue-on-error: true
        run: uv run pre-commit run --all-files
