name: Lint Code Base
on:
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7
        env:
          PYTHON_PYLINT_ARG_ARGUMENTS: "--disable=C0114,C0116"
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GITHUB_ADMIN_CUSTOM_LEVEL: true
          FIX_AUTOFIX: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push changes 
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Super-Linter: autoformatting"
